name: Release

on:
  push:
    tags:
      - '*'  # Trigger the workflow on any tag push

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      GO_VERSION: '1.22'
      VERSION: ${{ github.sha }}
      GIT_DEPTH: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}  # Ensure this is set in your repository secrets
